-- ============================================================
-- CI DEMO FILE — DO NOT MERGE
-- ============================================================
-- This file exists purely as a teaching prop for the Module 5
-- CI/CD lesson. It is a deliberately broken version of
-- int_inventory_resolved.sql designed to:
--
--   1. Trigger a failing CI job when submitted as a pull request
--   2. Show students that the assert_no_negative_margins.sql
--      singular test catches real model logic bugs, not just
--      missing data
--   3. Demonstrate that dbt Cloud's Slim CI job (state:modified+)
--      builds ONLY this model and its downstream dependents
--      (int_inventory_aging → fct_inventory) rather than the
--      full project
--
-- HOW TO USE IN CLASS:
--   Step 1: In your dbt Cloud Studio IDE, create a new branch
--           called "ci-demo-broken-margin"
--   Step 2: Open int_inventory_resolved.sql and replace line:
--             cost,
--           with:
--             -1 * cost as cost,     <- the bug
--   Step 3: Commit and open a Pull Request on GitHub
--   Step 4: Watch the CI job trigger automatically, build only
--           the affected models, and fail on the test
--   Step 5: Show students the failed job in dbt Cloud, the
--           failing test name, and the "merge blocked" status
--           on the PR in GitHub
--   Step 6: Fix the bug, push a new commit, and show the CI job
--           go green and unblock the merge
-- ============================================================

-- WHAT THE BUG DOES:
-- Changing `cost` to `-1 * cost` makes every item_margin positive
-- by an incorrect amount (it subtracts a negative cost, inflating
-- margin) — but more importantly, because int_inventory_resolved
-- feeds int_inventory_aging which feeds fct_inventory, and
-- int_order_items_joined also uses product cost, the knock-on
-- effects ripple downstream and cause assert_no_negative_margins
-- to catch items where the cost is now clearly wrong.

-- WHAT THE SLIM CI JOB WILL BUILD:
-- Because only int_inventory_resolved is changed on the branch,
-- dbt's state:modified+ selector will build:
--   int_inventory_resolved        (changed model)
--   int_inventory_aging           (downstream +1)
--   fct_inventory                 (downstream +2)
-- It will NOT rebuild the entire project -- this is the whole
-- point of Slim CI. Show students the job logs and count the
-- models built vs the total model count.

-- NO SQL NEEDED IN THIS FILE -- the bug is introduced by editing
-- the real int_inventory_resolved.sql directly on a branch.
-- This file is documentation only and belongs in ci/ not models/.
